# === Stage 47: Добавь финальную функцию demo(), которая показывает основной пользовательский сценарий ===
# Project: CourseSchedule
def demo():
    print("=== CourseSchedule Demo ===")
    schedule = CourseSchedule()
    schedule.add_professor("Иванов", "Математика")
    schedule.add_professor("Петрова", "Физика")
    schedule.add_professor("Сидоров", "Программирование")
    schedule.add_room("А-101", "Класс")
    schedule.add_room("А-201", "Лекторий")
    course = Course("Математика", "Мат101", "Иванов", "А-101")
    schedule.add_course(course)
    schedule.add_section(course, 1, "Понедельник", "10:00", "11:00", 30)
    section = schedule.get_section(course, 1)
    print(f"Курс: {course.name} ({course.code})")
    print(f"Преподаватель: {course.professor}")
    print(f"Аудитория: {course.room}")
    print(f"Секции: {len(schedule.get_sections(course))}")
    section2 = schedule.add_section(course, 2, "Среда", "14:00", "15:00", 30)
    attendance = schedule.get_attendance(section2)
    print(f"Посещаемость (Среда): {attendance['total']}/{attendance['max']}")
    schedule.add_attendance(section2, "Иванов", "Петрова", 28)
    attendance = schedule.get_attendance(section2)
    print(f"Посещаемость (Среда): {attendance['total']}/{attendance['max']}")
    schedule.print_schedule()
    schedule.print_statistics()
    print("=== Demo finished ===")
